baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Mr. Shawn"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/og-image.jpg"]

[module]
  [[module.imports]]
    path = 'https://github.com/adityatelange/hugo-PaperMod'
